import type { VideoItem } from "@/features/video-discovery/domain/video-item";

const VIDEO_CATALOG: VideoItem[] = [
  {
    id: "numbers-1-20",
    title: "Numbers 1 to 20",
    description: "Count in English with easy examples.",
    youtubeUrl: "https://www.youtube.com/watch?v=D0Ajq682yrA",
    thumbnailUrl: "https://img.youtube.com/vi/D0Ajq682yrA/hqdefault.jpg",
    level: "A1",
    tags: ["numbers", "counting"],
  },
  {
    id: "colors-for-kids",
    title: "Colors in English",
    description: "Learn color words with fun objects.",
    youtubeUrl: "https://www.youtube.com/watch?v=SLZcWGQQsmg",
    thumbnailUrl: "https://img.youtube.com/vi/SLZcWGQQsmg/hqdefault.jpg",
    level: "A1",
    tags: ["colors", "vocabulary"],
  },
  {
    id: "days-of-week",
    title: "Days of the Week Song",
    description: "Practice Monday to Sunday with rhythm.",
    youtubeUrl: "https://www.youtube.com/watch?v=36n93jvjkDs",
    thumbnailUrl: "https://img.youtube.com/vi/36n93jvjkDs/hqdefault.jpg",
    level: "A2",
    tags: ["days", "time", "song"],
  },
  {
    id: "animals-for-kids",
    title: "Animals and Sounds",
    description: "Say animal names and sounds in English.",
    youtubeUrl: "https://www.youtube.com/watch?v=rPe4yziWiOg",
    thumbnailUrl: "https://img.youtube.com/vi/rPe4yziWiOg/hqdefault.jpg",
    level: "A1",
    tags: ["animals", "vocabulary"],
  },
  {
    id: "numbers-1-100",
    title: "Numbers 1 to 100",
    description: "Numbers from 1 to 100 in English.",
    youtubeUrl: "https://www.youtube.com/watch?v=jlC2l0kqocE",
    thumbnailUrl: "https://img.youtube.com/vi/jlC2l0kqocE/hqdefault.jpg",
    level: "A1",
    tags: ["numbers", "counting"],
  },
  {
    id: "family-members",
    title: "Family Members Vocabulary",
    description: "Learn family words in English.",
    youtubeUrl: "https://www.youtube.com/watch?v=FHaObkHEkHQ",
    thumbnailUrl: "https://img.youtube.com/vi/FHaObkHEkHQ/hqdefault.jpg",
    level: "A1",
    tags: ["family", "vocabulary"],
  },
  {
    id: "body-parts-1",
    title: "Body Parts for Kids",
    description: "Learn body parts in English.",
    youtubeUrl: "https://www.youtube.com/watch?v=h4eueDYPTIg",
    thumbnailUrl: "https://img.youtube.com/vi/h4eueDYPTIg/hqdefault.jpg",
    level: "A1",
    tags: ["body", "vocabulary"],
  },
  {
    id: "months-year",
    title: "Months of the Year",
    description: "Learn the months in English.",
    youtubeUrl: "https://www.youtube.com/watch?v=Fe9bnYRzFvk",
    thumbnailUrl: "https://img.youtube.com/vi/Fe9bnYRzFvk/hqdefault.jpg",
    level: "A1",
    tags: ["months", "calendar"],
  },

  {
    id: "vegetables-vocabulary",
    title: "Vegetables Vocabulary Chant for Children",
    description: "Learn vegetable names in English with our Vegetables Chant.",
    youtubeUrl: "https://www.youtube.com/watch?v=TWpnohR6AoQ",
    thumbnailUrl: "https://img.youtube.com/vi/TWpnohR6AoQ/hqdefault.jpg",
    level: "A1",
    tags: ["food", "vocabulary"],
  },
  {
    id: "shapes-kids",
    title: "Shapes for Kids",
    description: "Learn basic shapes in English.",
    youtubeUrl: "https://www.youtube.com/watch?v=OEbRDtCAFdU",
    thumbnailUrl: "https://img.youtube.com/vi/OEbRDtCAFdU/hqdefault.jpg",
    level: "A2",
    tags: ["shapes", "geometry"],
  },
  {
    id: "jobs-professions",
    title: "Jobs and Occupations",
    description: "Learn common jobs in English.",
    youtubeUrl: "https://www.youtube.com/watch?v=ckKQclquAXU",
    thumbnailUrl: "https://img.youtube.com/vi/ckKQclquAXU/hqdefault.jpg",
    level: "A2",
    tags: ["jobs", "vocabulary"],
  },

  {
    id: "colors-basic",
    title: "Basic Colors",
    description: "Learn colors in English.",
    youtubeUrl: "https://www.youtube.com/watch?v=tRNy2i75tCc",
    thumbnailUrl: "https://img.youtube.com/vi/tRNy2i75tCc/hqdefault.jpg",
    level: "A1",
    tags: ["colors", "vocabulary"],
  },
  {
    id: "fruits-vegetables",
    title: "Fruits and Vegetables",
    description: "Learn food vocabulary.",
    youtubeUrl: "https://www.youtube.com/watch?v=MFmr_TZLpS0",
    thumbnailUrl: "https://img.youtube.com/vi/MFmr_TZLpS0/hqdefault.jpg",
    level: "A1",
    tags: ["food", "vocabulary"],
  },
  {
    id: "daily-routines",
    title: "Daily Routines",
    description: "Talk about daily activities.",
    youtubeUrl: "https://www.youtube.com/watch?v=qD1pnquN_DM",
    thumbnailUrl: "https://img.youtube.com/vi/qD1pnquN_DM/hqdefault.jpg",
    level: "A2",
    tags: ["routine", "speaking"],
  },
  {
    id: "clothes",
    title: "Clothes Vocabulary",
    description: "Learn clothes and accessories.",
    youtubeUrl: "https://www.youtube.com/watch?v=Q_EwuVHDb5U",
    thumbnailUrl: "https://img.youtube.com/vi/Q_EwuVHDb5U/hqdefault.jpg",
    level: "A2",
    tags: ["clothes", "fashion"],
  },
  {
    id: "school-supplies",
    title: "School Supplies",
    description: "Learn classroom vocabulary.",
    youtubeUrl: "https://www.youtube.com/watch?v=hjFaqDNUVFo",
    thumbnailUrl: "https://img.youtube.com/vi/hjFaqDNUVFo/hqdefault.jpg",
    level: "A2",
    tags: ["school", "vocabulary"],
  },
  {
    id: "telling-time",
    title: "Telling Time",
    description: "Learn how to say the time.",
    youtubeUrl: "https://www.youtube.com/watch?v=RBvmO7NgUp0",
    thumbnailUrl: "https://img.youtube.com/vi/RBvmO7NgUp0/hqdefault.jpg",
    level: "A2",
    tags: ["time", "grammar"],
  },
  {
    id: "places-town",
    title: "Places in Town",
    description: "Learn places around the city.",
    youtubeUrl: "https://www.youtube.com/watch?v=UdDXlL9u0vI",
    thumbnailUrl: "https://img.youtube.com/vi/UdDXlL9u0vI/hqdefault.jpg",
    level: "A2",
    tags: ["places", "city"],
  },
  {
    id: "greetings-basic",
    title: "Greetings for Kids",
    description: "Learn hello, goodbye and basic conversations.",
    youtubeUrl: "https://www.youtube.com/watch?v=tVlcKp3bWH8",
    thumbnailUrl: "https://img.youtube.com/vi/tVlcKp3bWH8/hqdefault.jpg",
    level: "A1",
    tags: ["greetings", "speaking"],
  },
  {
    id: "abc-phonics",
    title: "ABC Phonics Song",
    description: "Learn alphabet sounds in English.",
    youtubeUrl: "https://www.youtube.com/watch?v=BELlZKpi1Zs",
    thumbnailUrl: "https://img.youtube.com/vi/BELlZKpi1Zs/hqdefault.jpg",
    level: "A1",
    tags: ["alphabet", "phonics"],
  },
  {
    id: "numbers-1-10",
    title: "Numbers 1 to 10",
    description: "Learn numbers and counting.",
    youtubeUrl: "https://www.youtube.com/watch?v=85M1yxIcHpw",
    thumbnailUrl: "https://img.youtube.com/vi/85M1yxIcHpw/hqdefault.jpg",
    level: "A1",
    tags: ["numbers", "counting"],
  },
  {
    id: "animals-farm",
    title: "Farm Animals",
    description: "Learn farm animal names and sounds.",
    youtubeUrl: "https://www.youtube.com/watch?v=hewioIU4a64",
    thumbnailUrl: "https://img.youtube.com/vi/hewioIU4a64/hqdefault.jpg",
    level: "A1",
    tags: ["animals", "farm"],
  },
  {
    id: "fruits-vocabulary",
    title: "Fruits in English",
    description: "Learn apple, banana, orange and more.",
    youtubeUrl: "https://www.youtube.com/watch?v=mfReSbQ7jzE",
    thumbnailUrl: "https://img.youtube.com/vi/mfReSbQ7jzE/hqdefault.jpg",
    level: "A1",
    tags: ["fruits", "food"],
  },
  {
    id: "family-basic",
    title: "Family Members",
    description: "Learn mother, father, sister and brother.",
    youtubeUrl: "https://www.youtube.com/watch?v=GiRUF7hvWuM",
    thumbnailUrl: "https://img.youtube.com/vi/GiRUF7hvWuM/hqdefault.jpg",
    level: "A1",
    tags: ["family", "vocabulary"],
  },
  {
    id: "body-parts-basic-2",
    title: "Body Parts Song",
    description: "Learn body vocabulary for kids.",
    youtubeUrl: "https://www.youtube.com/watch?v=WX8HmogNyCY",
    thumbnailUrl: "https://img.youtube.com/vi/WX8HmogNyCY/hqdefault.jpg",
    level: "A1",
    tags: ["body", "vocabulary"],
  },
  {
    id: "classroom-objects",
    title: "Classroom Objects",
    description: "Learn school vocabulary.",
    youtubeUrl: "https://www.youtube.com/watch?v=dbklZrO5H78",
    thumbnailUrl: "https://img.youtube.com/vi/dbklZrO5H78/hqdefault.jpg",
    level: "A1",
    tags: ["school", "classroom"],
  },
  {
    id: "weather-kids",
    title: "Weather Vocabulary",
    description: "Learn sunny, rainy, cloudy and snowy.",
    youtubeUrl: "https://www.youtube.com/watch?v=XcW9Ct000yY",
    thumbnailUrl: "https://img.youtube.com/vi/XcW9Ct000yY/hqdefault.jpg",
    level: "A1",
    tags: ["weather", "vocabulary"],
  },
  {
    id: "transport-basic",
    title: "Transportation Vocabulary",
    description: "Learn car, bus, train and airplane.",
    youtubeUrl: "https://www.youtube.com/watch?v=0ynatfJauMk",
    thumbnailUrl: "https://img.youtube.com/vi/0ynatfJauMk/hqdefault.jpg",
    level: "A1",
    tags: ["transport", "vehicles"],
  },
  {
    id: "my-body-parts",
    title: "My Body Vocabulary Chant",
    description:
      "Learn parts of the body in English with our Body Vocabulary Chant",
    youtubeUrl: "https://www.youtube.com/watch?v=mOyriQBIFV4",
    thumbnailUrl: "https://img.youtube.com/vi/mOyriQBIFV4/hqdefault.jpg",
    level: "A1",
    tags: ["body", "vocabulary"],
  },
  {
    id: "feelings-emotions",
    title: "Feelings and Emotions",
    description: "Learn happy, sad, angry and excited.",
    youtubeUrl: "https://www.youtube.com/watch?v=l4WNrvVjiTw",
    thumbnailUrl: "https://img.youtube.com/vi/l4WNrvVjiTw/hqdefault.jpg",
    level: "A1",
    tags: ["feelings", "emotions"],
  },
  {
    id: "action-verbs",
    title: "Action Verbs",
    description: "Learn run, jump, eat, sleep and play.",
    youtubeUrl: "https://www.youtube.com/watch?v=VA00wkcxjTs",
    thumbnailUrl: "https://img.youtube.com/vi/VA00wkcxjTs/hqdefault.jpg",
    level: "A1",
    tags: ["verbs", "actions"],
  },

  {
    id: "healthy-food",
    title: "Healthy and Unhealthy Food",
    description: "Learn healthy food vocabulary.",
    youtubeUrl: "https://www.youtube.com/watch?v=fE8lezHs19s",
    thumbnailUrl: "https://img.youtube.com/vi/fE8lezHs19s/hqdefault.jpg",
    level: "A2",
    tags: ["food", "health"],
  },
  {
    id: "action-verbs-basic",
    title: "Action Verbs for Kids",
    description: "Learn common action verbs in English.",
    youtubeUrl: "https://www.youtube.com/watch?v=wwxgny8bvRE",
    thumbnailUrl: "https://img.youtube.com/vi/wwxgny8bvRE/hqdefault.jpg",
    level: "A1",
    tags: ["verbs", "actions"],
  },
  {
    id: "simple-action-words",
    title: "Simple Action Words",
    description: "Practice easy action words for beginners.",
    youtubeUrl: "https://www.youtube.com/watch?v=jV1o2g0E4H4",
    thumbnailUrl: "https://img.youtube.com/vi/jV1o2g0E4H4/hqdefault.jpg",
    level: "A1",
    tags: ["verbs", "actions"],
  },
  {
    id: "simple-present",
    title: "Simple Present Tense",
    description: "Learn simple present grammar.",
    youtubeUrl: "https://www.youtube.com/watch?v=wtTAdfyejH0",
    thumbnailUrl: "https://img.youtube.com/vi/wtTAdfyejH0/hqdefault.jpg",
    level: "A1",
    tags: ["grammar", "simple-present"],
  },
  {
    id: "verb-to-be",
    title: "Verb To Be",
    description: "Learn the verb 'to be' in simple present tense.",
    youtubeUrl: "https://www.youtube.com/watch?v=KRyK79yP0oA",
    thumbnailUrl: "https://img.youtube.com/vi/KRyK79yP0oA/hqdefault.jpg",
    level: "A1",
    tags: ["grammar", "simple-present"],
  },
  {
    id: "connectors-basic",
    title: "Basic Connectors",
    description: "Learn and, but, because and so.",
    youtubeUrl: "https://www.youtube.com/watch?v=tmerK-Fjc_s",
    thumbnailUrl: "https://img.youtube.com/vi/tmerK-Fjc_s/hqdefault.jpg",
    level: "A2",
    tags: ["grammar", "connectors"],
  },
  {
    id: "african-animals",
    title: "African Animals",
    description: "Learn safari animal names in English.",
    youtubeUrl: "https://www.youtube.com/watch?v=ka38mJFu5OU",
    thumbnailUrl: "https://img.youtube.com/vi/ka38mJFu5OU/hqdefault.jpg",
    level: "A1",
    tags: ["animals", "africa"],
  },
  {
    id: "food-song-kids",
    title: "Food Song for Kids",
    description: "Learn food vocabulary with songs.",
    youtubeUrl: "https://www.youtube.com/watch?v=6IwulRrYnzQ",
    thumbnailUrl: "https://img.youtube.com/vi/6IwulRrYnzQ/hqdefault.jpg",
    level: "A1",
    tags: ["food", "vocabulary"],
  },
  {
    id: "food-vocabulary-song",
    title: "Do You Like Food?",
    description: "Learn fruits, vegetables and desserts.",
    youtubeUrl: "https://www.youtube.com/watch?v=rjwrzBArZjA",
    thumbnailUrl: "https://img.youtube.com/vi/rjwrzBArZjA/hqdefault.jpg",
    level: "A1",
    tags: ["food", "vocabulary"],
  },
  {
    id: "likes-and-dislikes",
    title: "Likes and Dislikes for Kids",
    description: "Learn how to say what you like and dislike.",
    youtubeUrl: "https://www.youtube.com/watch?v=frN3nvhIHUk",
    thumbnailUrl: "https://img.youtube.com/vi/frN3nvhIHUk/hqdefault.jpg",
    level: "A1",
    tags: ["likes", "dislikes", "speaking"],
  },
  {
    id: "likes-and-dislikes-explained",
    title: "Likes and Dislikes Explained",
    description: "Learn how to say what you like and dislike.",
    youtubeUrl: "https://www.youtube.com/watch?v=O7AnqkMr2oI",
    thumbnailUrl: "https://img.youtube.com/vi/O7AnqkMr2oI/hqdefault.jpg",
    level: "A1",
    tags: ["likes", "dislikes", "speaking"],
  },
  {
    id: "have-has-basic",
    title: "Have and Has for Kids",
    description: "Learn when to use have and has.",
    youtubeUrl: "https://www.youtube.com/watch?v=8scxeHkopv8",
    thumbnailUrl: "https://img.youtube.com/vi/8scxeHkopv8/hqdefault.jpg",
    level: "A1",
    tags: ["grammar", "have", "has"],
  },
  {
    id: "hello-song",
    title: "Hello Song for Kids",
    description: "Learn greetings and introductions.",
    youtubeUrl: "https://www.youtube.com/watch?v=gghDRJVxFxU",
    thumbnailUrl: "https://img.youtube.com/vi/gghDRJVxFxU/hqdefault.jpg",
    level: "A1",
    tags: ["greetings", "speaking"],
  },
  {
    id: "alphabet-song",
    title: "ABC Alphabet Song",
    description: "Learn the English alphabet.",
    youtubeUrl: "https://www.youtube.com/watch?v=eegWzglBMh0",
    thumbnailUrl: "https://img.youtube.com/vi/eegWzglBMh0/hqdefault.jpg",
    level: "A1",
    tags: ["alphabet", "phonics"],
  },
  {
    id: "sea-animals",
    title: "Sea Animals for Kids",
    description: "Learn ocean animal names.",
    youtubeUrl: "https://www.youtube.com/watch?v=6-xqosckJ5c",
    thumbnailUrl: "https://img.youtube.com/vi/6-xqosckJ5c/hqdefault.jpg",
    level: "A1",
    tags: ["animals", "sea"],
  },
  {
    id: "pets-vocabulary",
    title: "Pets Vocabulary",
    description: "Learn common pets in English.",
    youtubeUrl: "https://www.youtube.com/watch?v=tj4JdexVNBA",
    thumbnailUrl: "https://img.youtube.com/vi/tj4JdexVNBA/hqdefault.jpg",
    level: "A1",
    tags: ["pets", "animals"],
  },
  {
    id: "present-continuous",
    title: "Present Continuous",
    description: "Learn verbs with ing.",
    youtubeUrl: "https://www.youtube.com/watch?v=lGkxRXamy7Y",
    thumbnailUrl: "https://img.youtube.com/vi/lGkxRXamy7Y/hqdefault.jpg",
    level: "A1",
    tags: ["grammar", "present-continuous"],
  },
    {
  id: "superheroes-vocabulary",
  title: "Superheroes for Kids",
  description: "Learn superhero vocabulary.",
  youtubeUrl: "https://www.youtube.com/watch?v=I4Wv3J2trMs",
  thumbnailUrl: "https://img.youtube.com/vi/I4Wv3J2trMs/hqdefault.jpg",
  level: "A1",
  tags: ["superheroes", "vocabulary"],
},
{
  id: "dinosaurs-for-kids",
  title: "Dinosaurs for Kids",
  description: "Learn dinosaur names in English.",
  youtubeUrl: "https://www.youtube.com/watch?v=j7uF-ZwalyA",
  thumbnailUrl: "https://img.youtube.com/vi/j7uF-ZwalyA/hqdefault.jpg",
  level: "A1",
  tags: ["dinosaurs", "animals"],
},
{
  id: "bugs-and-insects",
  title: "Bugs and Insects",
  description: "Learn insects vocabulary.",
  youtubeUrl: "https://www.youtube.com/watch?v=4b1LtGXC9FI",
  thumbnailUrl: "https://img.youtube.com/vi/4b1LtGXC9FI/hqdefault.jpg",
  level: "A1",
  tags: ["insects", "animals"],
},
{
  id: "sports-vocabulary",
  title: "Sports Vocabulary",
  description: "Learn sports names in English.",
  youtubeUrl: "https://www.youtube.com/watch?v=9AOAH0j14qQ",
  thumbnailUrl: "https://img.youtube.com/vi/9AOAH0j14qQ/hqdefault.jpg",
  level: "A1",
  tags: ["sports", "vocabulary"],
},
{
  id: "community-helpers",
  title: "Community Helpers",
  description: "Learn jobs and occupations.",
  youtubeUrl: "https://www.youtube.com/watch?v=jt2q1cHsH6E",
  thumbnailUrl: "https://img.youtube.com/vi/jt2q1cHsH6E/hqdefault.jpg",
  level: "A1",
  tags: ["jobs", "community"],
},
  
];



export function getStaticVideoCatalog(): VideoItem[] {
  return VIDEO_CATALOG;
}
