import type { VideoItem } from "@/features/video-discovery/domain/video-item";

const VIDEO_CATALOG: VideoItem[] = [
  {
    id: "numbers-1-20",
    title: "Numbers 1 to 20",
    description: "Count in English with easy examples.",
    youtubeUrl: "https://www.youtube.com/watch?v=D0Ajq682yrA",
    thumbnailUrl: "https://img.youtube.com/vi/D0Ajq682yrA/hqdefault.jpg",
    level: "A1",
    tags: ["numbers", "counting"],
    reference:
      "The Singing Walrus - English Songs For Kids. (2016, 25 febrero). Number song 1-20 for children | Counting numbers | The Singing Walrus [Vídeo]. YouTube. https://www.youtube.com/watch?v=D0Ajq682yrA",
  },
  {
    id: "colors-for-kids",
    title: "Colors in English",
    description: "Learn color words with fun objects.",
    youtubeUrl: "https://www.youtube.com/watch?v=SLZcWGQQsmg",
    thumbnailUrl: "https://img.youtube.com/vi/SLZcWGQQsmg/hqdefault.jpg",
    level: "A1",
    tags: ["colors", "vocabulary"],
    reference:
      "The Singing Walrus - English Songs For Kids. (2014, 20 mayo). Rainbow Colors Song | Colors Song for Kids | The Singing Walrus [Vídeo]. YouTube. https://www.youtube.com/watch?v=SLZcWGQQsmg",
  },
  {
    id: "days-of-week",
    title: "Days of the Week Song",
    description: "Practice Monday to Sunday with rhythm.",
    youtubeUrl: "https://www.youtube.com/watch?v=36n93jvjkDs",
    thumbnailUrl: "https://img.youtube.com/vi/36n93jvjkDs/hqdefault.jpg",
    level: "A2",
    tags: ["days", "time", "song"],
    reference:
      "Dream English Kids. (2011, 8 marzo). Days of The Week Song For Kids [Vídeo]. YouTube. https://www.youtube.com/watch?v=36n93jvjkDs",
  },
  {
    id: "animals-for-kids",
    title: "Animals and Sounds",
    description: "Say animal names and sounds in English.",
    youtubeUrl: "https://www.youtube.com/watch?v=rPe4yziWiOg",
    thumbnailUrl: "https://img.youtube.com/vi/rPe4yziWiOg/hqdefault.jpg",
    level: "A1",
    tags: ["animals", "vocabulary"],
    reference:
      "Blippi - Educational Videos for Kids. (2019, 19 enero). Blippi Learns about Jungle Animals for Kids | Educational Videos for Toddlers [Vídeo]. YouTube. https://www.youtube.com/watch?v=rPe4yziWiOg",
  },
  {
    id: "numbers-1-100",
    title: "Numbers 1 to 100",
    description: "Numbers from 1 to 100 in English.",
    youtubeUrl: "https://www.youtube.com/watch?v=jlC2l0kqocE",
    thumbnailUrl: "https://img.youtube.com/vi/jlC2l0kqocE/hqdefault.jpg",
    level: "A1",
    tags: ["numbers", "counting"],
    reference:
      "Amigo Mumu Español. (2020, 1 julio). Los Números en Inglés del 1 al 100 | Contar hasta el 100 en Inglés [Vídeo]. YouTube. https://www.youtube.com/watch?v=jlC2l0kqocE",
  },
  {
    id: "family-members",
    title: "Family Members Vocabulary",
    description: "Learn family words in English.",
    youtubeUrl: "https://www.youtube.com/watch?v=FHaObkHEkHQ",
    thumbnailUrl: "https://img.youtube.com/vi/FHaObkHEkHQ/hqdefault.jpg",
    level: "A1",
    tags: ["family", "vocabulary"],
    reference:
      "English Singsing. (2016, 14 junio). Family (family members & tree) - Kids vocabulary - Learn English educational video for kids [Vídeo]. YouTube. https://www.youtube.com/watch?v=FHaObkHEkHQ",
  },
  {
    id: "body-parts-1",
    title: "Body Parts for Kids",
    description: "Learn body parts in English.",
    youtubeUrl: "https://www.youtube.com/watch?v=h4eueDYPTIg",
    thumbnailUrl: "https://img.youtube.com/vi/h4eueDYPTIg/hqdefault.jpg",
    level: "A1",
    tags: ["body", "vocabulary"],
    reference:
      "ChuChu TV Nursery Rhymes & Kids Songs. (2014, 4 abril). Head, Shoulders, Knees & Toes - exercise song for kids [Vídeo]. YouTube. https://www.youtube.com/watch?v=h4eueDYPTIg",
  },
  {
    id: "months-year",
    title: "Months of the Year",
    description: "Learn the months in English.",
    youtubeUrl: "https://www.youtube.com/watch?v=Fe9bnYRzFvk",
    thumbnailUrl: "https://img.youtube.com/vi/Fe9bnYRzFvk/hqdefault.jpg",
    level: "A1",
    tags: ["months", "calendar"],
    reference:
      "The Singing Walrus - English Songs For Kids. (2016b, junio 15). Months of the Year Song | Song for Kids | The Singing Walrus [Vídeo]. YouTube. https://www.youtube.com/watch?v=Fe9bnYRzFvk",
  },
  {
    id: "vegetables-vocabulary",
    title: "Vegetables Vocabulary Chant for Children",
    description: "Learn vegetable names in English with our Vegetables Chant.",
    youtubeUrl: "https://www.youtube.com/watch?v=TWpnohR6AoQ",
    thumbnailUrl: "https://img.youtube.com/vi/TWpnohR6AoQ/hqdefault.jpg",
    level: "A1",
    tags: ["food", "vocabulary"],
    reference:
      "Fun Kids English. (2024, 21 febrero). Vegetables Vocabulary Chant for Children | Fun Kids English [Vídeo]. YouTube. https://www.youtube.com/watch?v=TWpnohR6AoQ",
  },
  {
    id: "shapes-kids",
    title: "Shapes for Kids",
    description: "Learn basic shapes in English.",
    youtubeUrl: "https://www.youtube.com/watch?v=OEbRDtCAFdU",
    thumbnailUrl: "https://img.youtube.com/vi/OEbRDtCAFdU/hqdefault.jpg",
    level: "A2",
    tags: ["shapes", "geometry"],
    reference:
      "The Singing Walrus - English Songs For Kids. (2015, 5 marzo). Shapes song for kids | The Singing Walrus [Vídeo]. YouTube. https://www.youtube.com/watch?v=OEbRDtCAFdU",
  },
  {
    id: "jobs-professions",
    title: "Jobs and Occupations",
    description: "Learn common jobs in English.",
    youtubeUrl: "https://www.youtube.com/watch?v=ckKQclquAXU",
    thumbnailUrl: "https://img.youtube.com/vi/ckKQclquAXU/hqdefault.jpg",
    level: "A2",
    tags: ["jobs", "vocabulary"],
    reference:
      "Fun Kids English. (2017, 29 junio). Jobs Song for Kids | What Do You Do? | Occupations | Kindergarten, Preschool, ESL | Fun Kids English [Vídeo]. YouTube. https://www.youtube.com/watch?v=ckKQclquAXU",
  },
  {
    id: "colors-basic",
    title: "Basic Colors",
    description: "Learn colors in English.",
    youtubeUrl: "https://www.youtube.com/watch?v=tRNy2i75tCc",
    thumbnailUrl: "https://img.youtube.com/vi/tRNy2i75tCc/hqdefault.jpg",
    level: "A1",
    tags: ["colors", "vocabulary"],
    reference:
      "KidsTV123. (2010, 20 junio). The Rainbow Colors song [Vídeo]. YouTube. https://www.youtube.com/watch?v=tRNy2i75tCc",
  },
  {
    id: "fruits-vegetables",
    title: "Fruits and Vegetables",
    description: "Learn food vocabulary.",
    youtubeUrl: "https://www.youtube.com/watch?v=MFmr_TZLpS0",
    thumbnailUrl: "https://img.youtube.com/vi/MFmr_TZLpS0/hqdefault.jpg",
    level: "A1",
    tags: ["food", "vocabulary"],
    reference:
      "Dr. Jean. (2010, 30 abril). Dr. Jean’s Banana Dance - (aka The Guacamole Song) [Vídeo]. YouTube. https://www.youtube.com/watch?v=MFmr_TZLpS0",
  },
  {
    id: "daily-routines",
    title: "Daily Routines",
    description: "Talk about daily activities.",
    youtubeUrl: "https://www.youtube.com/watch?v=qD1pnquN_DM",
    thumbnailUrl: "https://img.youtube.com/vi/qD1pnquN_DM/hqdefault.jpg",
    level: "A2",
    tags: ["routine", "speaking"],
    reference:
      "English Singsing. (2018, 24 mayo). My Day - Daily Routine - Kids vocabulary - Learn English for kids [Vídeo]. YouTube. https://www.youtube.com/watch?v=qD1pnquN_DM",
  },
  {
    id: "clothes",
    title: "Clothes Vocabulary",
    description: "Learn clothes and accessories.",
    youtubeUrl: "https://www.youtube.com/watch?v=Q_EwuVHDb5U",
    thumbnailUrl: "https://img.youtube.com/vi/Q_EwuVHDb5U/hqdefault.jpg",
    level: "A2",
    tags: ["clothes", "fashion"],
    reference:
      "English Singsing. (2016, 24 agosto). Clothes - clothing - Kids vocabulary - Learn English for kids [Vídeo]. YouTube. https://www.youtube.com/watch?v=Q_EwuVHDb5U",
  },
  {
    id: "school-supplies",
    title: "School Supplies",
    description: "Learn classroom vocabulary.",
    youtubeUrl: "https://www.youtube.com/watch?v=hjFaqDNUVFo",
    thumbnailUrl: "https://img.youtube.com/vi/hjFaqDNUVFo/hqdefault.jpg",
    level: "A2",
    tags: ["school", "vocabulary"],
    reference:
      "Fun Kids English. (2018, 1 agosto). School Supplies song | Fun Kids English [Vídeo]. YouTube. https://www.youtube.com/watch?v=hjFaqDNUVFo",
  },
  {
    id: "telling-time",
    title: "Telling Time",
    description: "Learn how to say the time.",
    youtubeUrl: "https://www.youtube.com/watch?v=RBvmO7NgUp0",
    thumbnailUrl: "https://img.youtube.com/vi/RBvmO7NgUp0/hqdefault.jpg",
    level: "A2",
    tags: ["time", "grammar"],
    reference:
      "Dream English Kids. (2016, 25 enero). Telling The Time Song for Kids | Dream English Kids [Vídeo]. YouTube. https://www.youtube.com/watch?v=RBvmO7NgUp0",
  },
  {
    id: "places-town",
    title: "Places in Town",
    description: "Learn places around the city.",
    youtubeUrl: "https://www.youtube.com/watch?v=UdDXlL9u0vI",
    thumbnailUrl: "https://img.youtube.com/vi/UdDXlL9u0vI/hqdefault.jpg",
    level: "A2",
    tags: ["places", "city"],
    reference:
      "English Singsing. (2018, 20 julio). Places in Town - Kids vocabulary - Learn English for kids [Vídeo]. YouTube. https://www.youtube.com/watch?v=UdDXlL9u0vI",
  },
  {
    id: "greetings-basic",
    title: "Greetings for Kids",
    description: "Learn hello, goodbye and basic conversations.",
    youtubeUrl: "https://www.youtube.com/watch?v=tVlcKp3bWH8",
    thumbnailUrl: "https://img.youtube.com/vi/tVlcKp3bWH8/hqdefault.jpg",
    level: "A1",
    tags: ["greetings", "speaking"],
    reference:
      "English Singsing. (2016, 12 julio). Greetings - Kids vocabulary - Learn English for kids [Vídeo]. YouTube. https://www.youtube.com/watch?v=tVlcKp3bWH8",
  },
  {
    id: "abc-phonics",
    title: "ABC Phonics Song",
    description: "Learn alphabet sounds in English.",
    youtubeUrl: "https://www.youtube.com/watch?v=BELlZKpi1Zs",
    thumbnailUrl: "https://img.youtube.com/vi/BELlZKpi1Zs/hqdefault.jpg",
    level: "A1",
    tags: ["alphabet", "phonics"],
    reference:
      "KidsTV123. (2009, 22 septiembre). Phonics Song 2 [Vídeo]. YouTube. https://www.youtube.com/watch?v=BELlZKpi1Zs",
  },
  {
    id: "numbers-1-10",
    title: "Numbers 1 to 10",
    description: "Learn numbers and counting.",
    youtubeUrl: "https://www.youtube.com/watch?v=85M1yxIcHpw",
    thumbnailUrl: "https://img.youtube.com/vi/85M1yxIcHpw/hqdefault.jpg",
    level: "A1",
    tags: ["numbers", "counting"],
    reference:
      "Dream English Kids. (2012, 17 mayo). Numbers Song Let’s Count 1-10 new version [Vídeo]. YouTube. https://www.youtube.com/watch?v=85M1yxIcHpw",
  },
  {
    id: "animals-farm",
    title: "Farm Animals",
    description: "Learn farm animal names and sounds.",
    youtubeUrl: "https://www.youtube.com/watch?v=hewioIU4a64",
    thumbnailUrl: "https://img.youtube.com/vi/hewioIU4a64/hqdefault.jpg",
    level: "A1",
    tags: ["animals", "farm"],
    reference:
      "Smile and Learn - English. (2019, 23 julio). Farm animals for kids - Vocabulary for kids [Vídeo]. YouTube. https://www.youtube.com/watch?v=hewioIU4a64",
  },
  {
    id: "fruits-vocabulary",
    title: "Fruits in English",
    description: "Learn apple, banana, orange and more.",
    youtubeUrl: "https://www.youtube.com/watch?v=mfReSbQ7jzE",
    thumbnailUrl: "https://img.youtube.com/vi/mfReSbQ7jzE/hqdefault.jpg",
    level: "A1",
    tags: ["fruits", "food"],
    reference:
      "The Singing Walrus - English Songs For Kids. (2015, 27 mayo). Fruit Song for Kids | The Singing Walrus [Vídeo]. YouTube. https://www.youtube.com/watch?v=mfReSbQ7jzE",
  },
  {
    id: "family-basic",
    title: "Family Members",
    description: "Learn mother, father, sister and brother.",
    youtubeUrl: "https://www.youtube.com/watch?v=GiRUF7hvWuM",
    thumbnailUrl: "https://img.youtube.com/vi/GiRUF7hvWuM/hqdefault.jpg",
    level: "A1",
    tags: ["family", "vocabulary"],
    reference:
      "ELF Kids Videos. (2010, 18 noviembre). We Are Family Song - My Family and ME! Acoustic Version - ELF Kids Videos [Vídeo]. YouTube. https://www.youtube.com/watch?v=GiRUF7hvWuM",
  },
  {
    id: "body-parts-basic-2",
    title: "Body Parts Song",
    description: "Learn body vocabulary for kids.",
    youtubeUrl: "https://www.youtube.com/watch?v=WX8HmogNyCY",
    thumbnailUrl: "https://img.youtube.com/vi/WX8HmogNyCY/hqdefault.jpg",
    level: "A1",
    tags: ["body", "vocabulary"],
    reference:
      "Super Simple Songs - Kids Songs. (2015, 15 julio). Head shoulders knees & toes (Speeding up) | Nursery Rhyme | Super Simple songs [Vídeo]. YouTube. https://www.youtube.com/watch?v=WX8HmogNyCY",
  },
  {
    id: "classroom-objects",
    title: "Classroom Objects",
    description: "Learn school vocabulary.",
    youtubeUrl: "https://www.youtube.com/watch?v=dbklZrO5H78",
    thumbnailUrl: "https://img.youtube.com/vi/dbklZrO5H78/hqdefault.jpg",
    level: "A1",
    tags: ["school", "classroom"],
    reference:
      "Super Simple Songs - Kids Songs. (2025, 28 agosto). Do you have a crayon? | School Supplies song | Super Simple songs [Vídeo]. YouTube. https://www.youtube.com/watch?v=dbklZrO5H78",
  },
  {
    id: "weather-kids",
    title: "Weather Vocabulary",
    description: "Learn sunny, rainy, cloudy and snowy.",
    youtubeUrl: "https://www.youtube.com/watch?v=XcW9Ct000yY",
    thumbnailUrl: "https://img.youtube.com/vi/XcW9Ct000yY/hqdefault.jpg",
    level: "A1",
    tags: ["weather", "vocabulary"],
    reference:
      "Dream English Kids. (2010, 10 agosto). Weather song for kids: The Sun Comes Up! [Vídeo]. YouTube. https://www.youtube.com/watch?v=XcW9Ct000yY",
  },
  {
    id: "transport-basic",
    title: "Transportation Vocabulary",
    description: "Learn car, bus, train and airplane.",
    youtubeUrl: "https://www.youtube.com/watch?v=0ynatfJauMk",
    thumbnailUrl: "https://img.youtube.com/vi/0ynatfJauMk/hqdefault.jpg",
    level: "A1",
    tags: ["transport", "vehicles"],
    reference:
      "Fun Kids English. (2023, 6 noviembre). Vehicles Vocabulary Chant for Children | Fun Kids English [Vídeo]. YouTube. https://www.youtube.com/watch?v=0ynatfJauMk",
  },
  {
    id: "my-body-parts",
    title: "My Body Vocabulary Chant",
    description:
      "Learn parts of the body in English with our Body Vocabulary Chant",
    youtubeUrl: "https://www.youtube.com/watch?v=mOyriQBIFV4",
    thumbnailUrl: "https://img.youtube.com/vi/mOyriQBIFV4/hqdefault.jpg",
    level: "A1",
    tags: ["body", "vocabulary"],
    reference:
      "Fun Kids English. (2025, 12 febrero). My Body Vocabulary Chant for Kindergarten Kids | Fun Kids English [Vídeo]. YouTube. https://www.youtube.com/watch?v=mOyriQBIFV4",
  },
  {
    id: "feelings-emotions",
    title: "Feelings and Emotions",
    description: "Learn happy, sad, angry and excited.",
    youtubeUrl: "https://www.youtube.com/watch?v=l4WNrvVjiTw",
    thumbnailUrl: "https://img.youtube.com/vi/l4WNrvVjiTw/hqdefault.jpg",
    level: "A1",
    tags: ["feelings", "emotions"],
    reference:
      "Super Simple Songs - Kids Songs. (2013, 22 noviembre). If You’re Happy | Kids Song | Super Simple Songs [Vídeo]. YouTube. https://www.youtube.com/watch?v=l4WNrvVjiTw",
  },
  {
    id: "action-verbs",
    title: "Action Verbs",
    description: "Learn run, jump, eat, sleep and play.",
    youtubeUrl: "https://www.youtube.com/watch?v=VA00wkcxjTs",
    thumbnailUrl: "https://img.youtube.com/vi/VA00wkcxjTs/hqdefault.jpg",
    level: "A1",
    tags: ["verbs", "actions"],
    reference:
      "Inglés para niños con Mr Pea. (2025, 21 marzo). 10 «ACTION VERBS» SUPER ÚTILES - INGLÉS PARA NIÑOS CON MR.PEA [Vídeo]. YouTube. https://www.youtube.com/watch?v=VA00wkcxjTs",
  },
  {
    id: "healthy-food",
    title: "Healthy and Unhealthy Food",
    description: "Learn healthy food vocabulary.",
    youtubeUrl: "https://www.youtube.com/watch?v=fE8lezHs19s",
    thumbnailUrl: "https://img.youtube.com/vi/fE8lezHs19s/hqdefault.jpg",
    level: "A2",
    tags: ["food", "health"],
    reference:
      "English Tree. (2016, 29 octubre). Healthy Food vs junk Food song! [Vídeo]. YouTube. https://www.youtube.com/watch?v=fE8lezHs19s",
  },
  {
    id: "action-verbs-basic",
    title: "Action Verbs for Kids",
    description: "Learn common action verbs in English.",
    youtubeUrl: "https://www.youtube.com/watch?v=wwxgny8bvRE",
    thumbnailUrl: "https://img.youtube.com/vi/wwxgny8bvRE/hqdefault.jpg",
    level: "A1",
    tags: ["verbs", "actions"],
    reference:
      "Baby Nenes. (2017, 6 marzo). Verbos básicos en inglés y español para niños (basic verbs) [Vídeo]. YouTube. https://www.youtube.com/watch?v=wwxgny8bvRE",
  },
  {
    id: "simple-action-words",
    title: "Simple Action Words",
    description: "Practice easy action words for beginners.",
    youtubeUrl: "https://www.youtube.com/watch?v=jV1o2g0E4H4",
    thumbnailUrl: "https://img.youtube.com/vi/jV1o2g0E4H4/hqdefault.jpg",
    level: "A1",
    tags: ["verbs", "actions"],
    reference:
      "World of Dhiyara. (2021, 26 agosto). ACTION VERBS FOR KIDS | HOW TO TEACH SIMPLE ACTION WORDS TO TODDLERS [Vídeo]. YouTube. https://www.youtube.com/watch?v=jV1o2g0E4H4",
  },
  {
    id: "simple-present",
    title: "Simple Present Tense",
    description: "Learn simple present grammar.",
    youtubeUrl: "https://www.youtube.com/watch?v=wtTAdfyejH0",
    thumbnailUrl: "https://img.youtube.com/vi/wtTAdfyejH0/hqdefault.jpg",
    level: "A1",
    tags: ["grammar", "simple-present"],
    reference:
      "Inglés para niños con Mr Pea. (2020, 11 agosto). PRESENT SIMPLE INGLÉS PARA NIÑOS CON MR PEA ENGLISH FOR KIDS [Vídeo]. YouTube. https://www.youtube.com/watch?v=wtTAdfyejH0",
  },
  {
    id: "verb-to-be",
    title: "Verb To Be",
    description: "Learn the verb 'to be' in simple present tense.",
    youtubeUrl: "https://www.youtube.com/watch?v=KRyK79yP0oA",
    thumbnailUrl: "https://img.youtube.com/vi/KRyK79yP0oA/hqdefault.jpg",
    level: "A1",
    tags: ["grammar", "simple-present"],
    reference:
      "Amigo Mumu Español. (2023, 11 mayo). EL VERBO TO BE EN INGLÉS DE MANERA FÁCIL y RÁPIDA | CLASE DE INGLÉS AMIGO MUMU [Vídeo]. YouTube. https://www.youtube.com/watch?v=KRyK79yP0oA",
  },
  {
    id: "connectors-basic",
    title: "Basic Connectors",
    description: "Learn and, but, because and so.",
    youtubeUrl: "https://www.youtube.com/watch?v=tmerK-Fjc_s",
    thumbnailUrl: "https://img.youtube.com/vi/tmerK-Fjc_s/hqdefault.jpg",
    level: "A2",
    tags: ["grammar", "connectors"],
    reference:
      "Inglés para niños con Mr Pea. (2023, 12 enero). CONECTORES BÁSICOS EN INGLÉS - INGLÉS PARA NIÑOS CON MR.PEA [Vídeo]. YouTube. https://www.youtube.com/watch?v=tmerK-Fjc_s",
  },
  {
    id: "african-animals",
    title: "African Animals",
    description: "Learn safari animal names in English.",
    youtubeUrl: "https://www.youtube.com/watch?v=ka38mJFu5OU",
    thumbnailUrl: "https://img.youtube.com/vi/ka38mJFu5OU/hqdefault.jpg",
    level: "A1",
    tags: ["animals", "africa"],
    reference:
      "Smart Family: Learn English. (2018, 29 enero). African Animals in English 🦓 | Listen and Repeat Wild Animal Words 🎧 [Vídeo]. YouTube. https://www.youtube.com/watch?v=ka38mJFu5OU",
  },
  {
    id: "food-song-kids",
    title: "Food Song for Kids",
    description: "Learn food vocabulary with songs.",
    youtubeUrl: "https://www.youtube.com/watch?v=6IwulRrYnzQ",
    thumbnailUrl: "https://img.youtube.com/vi/6IwulRrYnzQ/hqdefault.jpg",
    level: "A1",
    tags: ["food", "vocabulary"],
    reference:
      "Dream English Kids. (2016b, enero 25). Food Song | Learn 15 Food and Drinks | Learn English Kids [Vídeo]. YouTube. https://www.youtube.com/watch?v=6IwulRrYnzQ",
  },
  {
    id: "food-vocabulary-song",
    title: "Do You Like Food?",
    description: "Learn fruits, vegetables and desserts.",
    youtubeUrl: "https://www.youtube.com/watch?v=rjwrzBArZjA",
    thumbnailUrl: "https://img.youtube.com/vi/rjwrzBArZjA/hqdefault.jpg",
    level: "A1",
    tags: ["food", "vocabulary"],
    reference:
      "Super English Kid. (2016, 11 junio). Do you like food? Song for kids. | Super English Kid! [Vídeo]. YouTube. https://www.youtube.com/watch?v=rjwrzBArZjA",
  },
  {
    id: "likes-and-dislikes",
    title: "Likes and Dislikes for Kids",
    description: "Learn how to say what you like and dislike.",
    youtubeUrl: "https://www.youtube.com/watch?v=frN3nvhIHUk",
    thumbnailUrl: "https://img.youtube.com/vi/frN3nvhIHUk/hqdefault.jpg",
    level: "A1",
    tags: ["likes", "dislikes", "speaking"],
    reference:
      "Super Simple Songs - Kids Songs. (2013, 9 octubre). Do You Like Broccoli Ice Cream? | Food Song for Kids! [Vídeo]. YouTube. https://www.youtube.com/watch?v=frN3nvhIHUk",
  },
  {
    id: "likes-and-dislikes-explained",
    title: "Likes and Dislikes Explained",
    description: "Learn how to say what you like and dislike.",
    youtubeUrl: "https://www.youtube.com/watch?v=O7AnqkMr2oI",
    thumbnailUrl: "https://img.youtube.com/vi/O7AnqkMr2oI/hqdefault.jpg",
    level: "A1",
    tags: ["likes", "dislikes", "speaking"],
    reference:
      "Inglés para niños con Mr Pea. (2020, 16 agosto). LIKE & DISLIKE EN INGLÉS (PREFERENCIAS) - INGLÉS PARA NIÑOS CON MR PEA [Vídeo]. YouTube. https://www.youtube.com/watch?v=O7AnqkMr2oI",
  },
  {
    id: "have-has-basic",
    title: "Have and Has for Kids",
    description: "Learn when to use have and has.",
    youtubeUrl: "https://www.youtube.com/watch?v=8scxeHkopv8",
    thumbnailUrl: "https://img.youtube.com/vi/8scxeHkopv8/hqdefault.jpg",
    level: "A1",
    tags: ["grammar", "have", "has"],
    reference:
      "Interesting English. (2026, 20 enero). Have — Has for kids | English Grammar [Vídeo]. YouTube. https://www.youtube.com/watch?v=8scxeHkopv8",
  },
  {
    id: "hello-song",
    title: "Hello Song for Kids",
    description: "Learn greetings and introductions.",
    youtubeUrl: "https://www.youtube.com/watch?v=gghDRJVxFxU",
    thumbnailUrl: "https://img.youtube.com/vi/gghDRJVxFxU/hqdefault.jpg",
    level: "A1",
    tags: ["greetings", "speaking"],
    reference:
      "Super Simple Songs - Kids Songs. (2005, 22 septiembre). Hello! | Super Simple Songs [Vídeo]. YouTube. https://www.youtube.com/watch?v=gghDRJVxFxU",
  },
  {
    id: "alphabet-song",
    title: "ABC Alphabet Song",
    description: "Learn the English alphabet.",
    youtubeUrl: "https://www.youtube.com/watch?v=eegWzglBMh0",
    thumbnailUrl: "https://img.youtube.com/vi/eegWzglBMh0/hqdefault.jpg",
    level: "A1",
    tags: ["alphabet", "phonics"],
    reference:
      "Lingokids Official Channel. (2020, 13 enero). ABCD In the Morning Brush your Teeth 🎵 ABC SONG | Lingokids [Vídeo]. YouTube. https://www.youtube.com/watch?v=eegWzglBMh0",
  },
  {
    id: "sea-animals",
    title: "Sea Animals for Kids",
    description: "Learn ocean animal names.",
    youtubeUrl: "https://www.youtube.com/watch?v=6-xqosckJ5c",
    thumbnailUrl: "https://img.youtube.com/vi/6-xqosckJ5c/hqdefault.jpg",
    level: "A1",
    tags: ["animals", "sea"],
    reference:
      "The Kiboomers - Kids Music Channel. (2016, 18 marzo). Animals In The Ocean Lyric Video [Vídeo]. YouTube. https://www.youtube.com/watch?v=6-xqosckJ5c",
  },
  {
    id: "pets-vocabulary",
    title: "Pets Vocabulary",
    description: "Learn common pets in English.",
    youtubeUrl: "https://www.youtube.com/watch?v=tj4JdexVNBA",
    thumbnailUrl: "https://img.youtube.com/vi/tj4JdexVNBA/hqdefault.jpg",
    level: "A1",
    tags: ["pets", "animals"],
    reference:
      "Fun Kids English. (2024, 9 enero). Pets Vocabulary Chant for Children | Fun Kids English [Vídeo]. YouTube. https://www.youtube.com/watch?v=tj4JdexVNBA",
  },
  {
    id: "present-continuous",
    title: "Present Continuous",
    description: "Learn verbs with ing.",
    youtubeUrl: "https://www.youtube.com/watch?v=lGkxRXamy7Y",
    thumbnailUrl: "https://img.youtube.com/vi/lGkxRXamy7Y/hqdefault.jpg",
    level: "A1",
    tags: ["grammar", "present-continuous"],
    reference:
      "Inglés para niños con Mr Pea. (2020b, diciembre 18). PRESENT CONTINUOUS (EXPLICACIÓN + PRÁCTICA) - INGLÉS PARA NIÑOS CON MR.PEA [Vídeo]. YouTube. https://www.youtube.com/watch?v=lGkxRXamy7Y",
  },
];

export function getStaticVideoCatalog(): VideoItem[] {
  return VIDEO_CATALOG;
}
